version: '3.8'

services:
  meta-automl:
    image: jcuzcoucuenca/generacion-pipelines:latest
    container_name: meta-automl-container
    command: python main.py

    env_file:
      - .env

    cpus: 4.0
    mem_limit: 8g

    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all